### PR TITLE
Add upload command, auto upload setting

### PR DESCRIPTION
**Pull request by nella17**

### CODE REVIEW

**Comment by cyanzhong** [comment]
Looks like a nice change, I need to review & test it before merge.

Thank you!

**Comment by cyanzhong** [comment]
I have a question here, looks like the default value of `autoUpload` is `false`.

Can you explain a little bit in what situation that user doesn't want to sync the file automatically?

**Comment by nella17** [comment]
平常有在寫 `JavaScript` 的使用者，不希望自動上傳。
不過我會關閉擴充功能，只在某個目錄開啟。
因為這個擴充功能有一些 snippets 在其他的環境不能用。
把預設值調整成 `true` 好像會更好？

**Comment by nella17** [comment]
`Host` 使用 `My-iPhone.local` 會更好。
```javascript
let host = $device.info.name.replace(" ", "-") + ".local";
$ui.alert({
  title: "Device Host",
  message: host,
})
$clipboard.copy({
  "text": host
})
```

**Pull request merged**
