### PR TITLE
Add support for multiple Hosts

### PR DESCRIPTION
**Pull request by fcrespo82**
Hi! In this pull request I added the ability to sync to various devices at once.

Maybe it can be improved by selective sync distinct files to different devices, but for now I kept it simple.

Please feel free for any feedback.

Hope you enjoy it!

### CODE REVIEW

**Comment by cyanzhong** [comment]
Sorry, I didn't notice this one (and another one), I will take a look.

Thanks!

**Comment by fcrespo82** [comment]
No problem! Happy to help!

**Review by cyanzhong — COMMENTED** [review]
This change is super cool! I saw some wrong indentations, can you fix them before we merge it? Thanks.

**Comment by fcrespo82** [comment]
Done! If you find any other issues, please let me know!

**Comment by cyanzhong** [comment]
Thanks!

**Pull request merged**
